
-- 1. BORRADO DE TABLAS

DROP TABLE Historial_visita CASCADE CONSTRAINTS;
DROP TABLE Factura_cliente CASCADE CONSTRAINTS;
DROP TABLE Pago_detalle CASCADE CONSTRAINTS;
DROP TABLE Multa CASCADE CONSTRAINTS;
DROP TABLE Cuota_generada CASCADE CONSTRAINTS;
DROP TABLE Pago CASCADE CONSTRAINTS;
DROP TABLE Tipo_pago_os CASCADE CONSTRAINTS;
DROP TABLE casa_residente CASCADE CONSTRAINTS;
DROP TABLE Residente CASCADE CONSTRAINTS;
DROP TABLE Casa CASCADE CONSTRAINTS;
DROP TABLE Cat_mensualidad CASCADE CONSTRAINTS;
DROP TABLE Usuario_empleado CASCADE CONSTRAINTS;
DROP TABLE Perfil_usuario CASCADE CONSTRAINTS;
DROP TABLE Modulo_acceso_usuario_os CASCADE CONSTRAINTS;


-- 2. CREACIÓN DE TABLAS


-- 2.1 Módulos de Acceso
CREATE TABLE Modulo_acceso_usuario_os (
    id_modulo_acceso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    activo_si_no NUMBER(1)
);

-- 2.2 Perfiles de Usuario
CREATE TABLE Perfil_usuario (
    id_perfil_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    id_modulo_acceso NUMBER,
    CONSTRAINT fk_perfil_modulo FOREIGN KEY (id_modulo_acceso) REFERENCES Modulo_acceso_usuario_os(id_modulo_acceso)
);

-- 2.3 Empleados (Se crea con 'contraseña' para luego alterarla según tu flujo)
CREATE TABLE Usuario_empleado (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fotografia BLOB,
    dpi NUMBER,
    primer_nombre VARCHAR2(50),
    segundo_nombre VARCHAR2(50),
    primer_apellido VARCHAR2(50),
    segundo_apellido VARCHAR2(50),
    direccion_unificada VARCHAR2(255),
    avenida VARCHAR2(50),
    zona_numero NUMBER,
    municipio VARCHAR2(100),
    departamento VARCHAR2(100),
    codigo_postal NUMBER,
    telefono NUMBER,
    contraseña VARCHAR2(255),
    correo_electronico VARCHAR2(100),
    activo_si_no NUMBER(1),
    id_perfil_usuario NUMBER,
    CONSTRAINT fk_usuario_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES Perfil_usuario(id_perfil_usuario)
);

-- 2.4 Catálogo de Mensualidades
CREATE TABLE Cat_mensualidad (
    id_mensualidad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100),
    monto NUMBER(10,2),
    cantidad NUMBER
);

-- 2.5 Casas
CREATE TABLE Casa (
    id_casa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion_unificada VARCHAR2(255),
    avenida VARCHAR2(50),
    zona_numero NUMBER,
    municipio VARCHAR2(100),
    departamento VARCHAR2(100),
    codigo_postal NUMBER,
    descripcion VARCHAR2(255),
    foto_principal BLOB,
    id_mensualidad NUMBER,
    CONSTRAINT fk_casa_mensualidad FOREIGN KEY (id_mensualidad) REFERENCES Cat_mensualidad(id_mensualidad)
);

-- 2.6 Residentes
CREATE TABLE Residente (
    id_residente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primer_nombre VARCHAR2(50),
    segundo_nombre VARCHAR2(50),
    primer_apellido VARCHAR2(50),
    segundo_apellido VARCHAR2(50),
    direccion_unificada VARCHAR2(255),
    avenida VARCHAR2(50),
    zona_numero NUMBER,
    municipio VARCHAR2(100),
    departamento VARCHAR2(100),
    codigo_postal NUMBER,
    telefono NUMBER,
    correo VARCHAR2(100),
    fecha_registro DATE,
    fecha_dado_baja DATE,
    dpi NUMBER,
    activo_si_no NUMBER(1)
);

-- 2.7 Tabla Intermedia: Casa_Residente
CREATE TABLE casa_residente (
    id_casa NUMBER,
    id_residente NUMBER,
    PRIMARY KEY (id_casa, id_residente),
    CONSTRAINT fk_cr_casa FOREIGN KEY (id_casa) REFERENCES Casa(id_casa),
    CONSTRAINT fk_cr_residente FOREIGN KEY (id_residente) REFERENCES Residente(id_residente)
);

-- 2.8 Tipos de Pago
CREATE TABLE Tipo_pago_os (
    id_tipo_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    activo_si_no NUMBER(1)
);

-- 2.9 Pagos
CREATE TABLE Pago (
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_casa NUMBER,
    id_tipo_pago NUMBER,
    monto NUMBER(10,2),
    numero_referencia VARCHAR2(50),
    fecha_pago DATE,
    comprobante_url VARCHAR2(255),
    CONSTRAINT fk_pago_casa FOREIGN KEY (id_casa) REFERENCES Casa(id_casa),
    CONSTRAINT fk_pago_tipo FOREIGN KEY (id_tipo_pago) REFERENCES Tipo_pago_os(id_tipo_pago)
);

-- 2.10 Cuotas Generadas
CREATE TABLE Cuota_generada (
    id_cuota NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_casa NUMBER,
    monto_a_cobrar NUMBER(10,2),
    fecha_emision DATE,
    estado VARCHAR2(50),
    CONSTRAINT fk_cuota_casa FOREIGN KEY (id_casa) REFERENCES Casa(id_casa)
);

-- 2.11 Multas
CREATE TABLE Multa (
    id_multa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(255),
    precio NUMBER(10,2),
    id_casa NUMBER,
    id_numero_referencia VARCHAR2(50),
    CONSTRAINT fk_multa_casa FOREIGN KEY (id_casa) REFERENCES Casa(id_casa)
);

-- 2.12 Detalle de Pagos
CREATE TABLE Pago_detalle (
    id_pago_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pago NUMBER,
    id_cuota NUMBER,
    id_multa NUMBER,
    monto_aplicado NUMBER(10,2),
    CONSTRAINT fk_det_pago FOREIGN KEY (id_pago) REFERENCES Pago(id_pago),
    CONSTRAINT fk_det_cuota FOREIGN KEY (id_cuota) REFERENCES Cuota_generada(id_cuota),
    CONSTRAINT fk_det_multa FOREIGN KEY (id_multa) REFERENCES Multa(id_multa)
);

-- 2.13 Facturas
CREATE TABLE Factura_cliente (
    id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pago NUMBER,
    id_empleado NUMBER,
    codigo VARCHAR2(50),
    correlativo NUMBER,
    fecha_inicio DATE,
    fecha_final DATE,
    total NUMBER(10,2),
    CONSTRAINT fk_factura_pago FOREIGN KEY (id_pago) REFERENCES Pago(id_pago),
    CONSTRAINT fk_factura_empleado FOREIGN KEY (id_empleado) REFERENCES Usuario_empleado(id_empleado)
);

-- 2.14 Historial de Visitas
CREATE TABLE Historial_visita (
    id_historial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    apellido VARCHAR2(50),
    dpi NUMBER,
    observaciones VARCHAR2(255),
    id_casa NUMBER,
    fecha_entrada DATE,
    fecha_salida DATE,
    id_empleado NUMBER,
    CONSTRAINT fk_visita_casa FOREIGN KEY (id_casa) REFERENCES Casa(id_casa),
    CONSTRAINT fk_visita_empleado FOREIGN KEY (id_empleado) REFERENCES Usuario_empleado(id_empleado)
);


-- 3. ALTERS (MODIFICACIONES DE ESTRUCTURA REQUERIDAS)

ALTER TABLE Usuario_empleado MODIFY contraseña VARCHAR2(255);
ALTER TABLE Usuario_empleado RENAME COLUMN contraseña TO PASSWORD_HASH;


-- 4. INSERTS (DUMMY DATA PARA PRUEBAS)

SET DEFINE OFF;

-- Módulos
INSERT INTO Modulo_acceso_usuario_os (nombre, activo_si_no) VALUES ('Administración Total', 1);
INSERT INTO Modulo_acceso_usuario_os (nombre, activo_si_no) VALUES ('Control de Garita', 1);

-- Perfiles
INSERT INTO Perfil_usuario (nombre, id_modulo_acceso) VALUES ('Super Admin', 1);
INSERT INTO Perfil_usuario (nombre, id_modulo_acceso) VALUES ('Seguridad', 2);

-- Empleados
INSERT INTO Usuario_empleado (primer_nombre, primer_apellido, dpi, PASSWORD_HASH, correo_electronico, id_perfil_usuario, activo_si_no) 
VALUES ('Diego', 'Flores', 1234567890101, '$2b$10$Bec3A6v3MUOHoyjtye8/seRncz.Q93o8XrkXq7sm00Y5LrUiPfLdC', 'admin@condogest.com', 1, 1);
INSERT INTO Usuario_empleado (primer_nombre, primer_apellido, dpi, PASSWORD_HASH, correo_electronico, id_perfil_usuario, activo_si_no) 
VALUES ('Carlos', 'Mazariegos', 3001458790101, 'hash_secreta_2026', 'carlos.garita@condogest.com', 2, 1);

-- Mensualidades
INSERT INTO Cat_mensualidad (descripcion, monto, cantidad) VALUES ('Mantenimiento Ordinario', 350.00, 1);
INSERT INTO Cat_mensualidad (descripcion, monto, cantidad) VALUES ('Mantenimiento + Casa Club', 500.00, 1);

-- Casas
INSERT INTO Casa (direccion_unificada, avenida, zona_numero, municipio, departamento, id_mensualidad) 
VALUES ('Manzana A Lote 5', 'Boulevard Principal', 10, 'Villa Nueva', 'Guatemala', 1);
INSERT INTO Casa (direccion_unificada, avenida, zona_numero, municipio, departamento, id_mensualidad) 
VALUES ('Manzana C Lote 12', 'Calle de los Pinos', 10, 'Villa Nueva', 'Guatemala', 2);

-- Residentes
INSERT INTO Residente (primer_nombre, primer_apellido, dpi, telefono, correo, activo_si_no, fecha_registro) 
VALUES ('Juan', 'Gómez', 2541896320101, 55443322, 'juan.gomez@email.com', 1, TO_DATE('2026-01-15', 'YYYY-MM-DD'));
INSERT INTO Residente (primer_nombre, primer_apellido, dpi, telefono, correo, activo_si_no, fecha_registro) 
VALUES ('Maria', 'López', 1587423690101, 44112233, 'm.lopez@email.com', 1, TO_DATE('2026-02-20', 'YYYY-MM-DD'));

-- Relaciones Casa-Residente
INSERT INTO casa_residente (id_casa, id_residente) VALUES (1, 1);
INSERT INTO casa_residente (id_casa, id_residente) VALUES (2, 2);

-- Tipos de Pago
INSERT INTO Tipo_pago_os (nombre, activo_si_no) VALUES ('Transferencia Bancaria', 1);
INSERT INTO Tipo_pago_os (nombre, activo_si_no) VALUES ('Depósito Monetario', 1);

-- Cuotas
INSERT INTO Cuota_generada (id_casa, monto_a_cobrar, fecha_emision, estado) VALUES (1, 350.00, SYSDATE, 'Pendiente');

-- Visitas
INSERT INTO Historial_visita (nombre, apellido, dpi, observaciones, id_casa, fecha_entrada, id_empleado)
VALUES ('Estuardo', 'Ruiz', 4455889960101, 'Entrega de comida rápida', 1, SYSDATE, 2);

COMMIT;


-- 5. VERIFICACIÓN

SELECT * FROM Usuario_empleado;
